// GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.
// Fucsia tokens for the CmuxDock tile.

import AppKit

enum Iris {
    static let bgBase     = NSColor(srgbRed: 0.0471, green: 0.0353, blue: 0.0510, alpha: 1) // #0c090d
    static let bgRaised   = NSColor(srgbRed: 0.0863, green: 0.0706, blue: 0.0941, alpha: 1) // #161218
    static let bgPanel    = NSColor(srgbRed: 0.1294, green: 0.1098, blue: 0.1373, alpha: 1) // #211c23
    static let bgChrome   = NSColor(srgbRed: 0.2667, green: 0.2471, blue: 0.2745, alpha: 1) // #443f46  — system bar / notch island
    static let border     = NSColor(srgbRed: 0.2471, green: 0.2235, blue: 0.2549, alpha: 1) // #3f3941
    static let textDim    = NSColor(srgbRed: 0.4706, green: 0.4471, blue: 0.4784, alpha: 1) // #78727a
    static let text       = NSColor(srgbRed: 0.8078, green: 0.7961, blue: 0.8157, alpha: 1) // #cecbd0
    static let textBright = NSColor(srgbRed: 0.9451, green: 0.9373, blue: 0.9490, alpha: 1) // #f1eff2

    // Identity. Used for the resting ring only — never to signal a state.
    static let accent     = NSColor(srgbRed: 0.8784, green: 0.4667, blue: 0.8471, alpha: 1) // #e077d8

    // States. Ranked worst-wins by the tile.
    static let info       = NSColor(srgbRed: 0.3098, green: 0.8039, blue: 0.8039, alpha: 1) // #4fcdcd  — working
    static let warning    = NSColor(srgbRed: 0.9451, green: 0.7490, blue: 0.3059, alpha: 1) // #f1bf4e  — needs attention
    static let error      = NSColor(srgbRed: 0.9490, green: 0.3059, blue: 0.3373, alpha: 1) // #f24e56  — failed

    // Lifted for the notch island, which sits on bgChrome.
    static let infoUp     = NSColor(srgbRed: 0.5020, green: 0.8980, blue: 0.8941, alpha: 1) // #80e5e4
    static let warningUp  = NSColor(srgbRed: 1.0000, green: 0.8510, blue: 0.5333, alpha: 1) // #ffd988
    static let errorUp    = NSColor(srgbRed: 1.0000, green: 0.5843, blue: 0.5725, alpha: 1) // #ff9592
    static let accentUp   = NSColor(srgbRed: 0.9608, green: 0.6745, blue: 0.9333, alpha: 1) // #f5acee
}
