// GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.
// Azur tokens for the CmuxDock tile.

import AppKit

enum Iris {
    static let bgBase     = NSColor(srgbRed: 0.0196, green: 0.0431, blue: 0.0510, alpha: 1) // #050b0d
    static let bgRaised   = NSColor(srgbRed: 0.0471, green: 0.0863, blue: 0.0902, alpha: 1) // #0c1617
    static let bgPanel    = NSColor(srgbRed: 0.0863, green: 0.1255, blue: 0.1333, alpha: 1) // #162022
    static let bgChrome   = NSColor(srgbRed: 0.2235, green: 0.2627, blue: 0.2706, alpha: 1) // #394345  — system bar / notch island
    static let border     = NSColor(srgbRed: 0.1961, green: 0.2431, blue: 0.2549, alpha: 1) // #323e41
    static let textDim    = NSColor(srgbRed: 0.4235, green: 0.4667, blue: 0.4745, alpha: 1) // #6c7779
    static let text       = NSColor(srgbRed: 0.7804, green: 0.8078, blue: 0.8118, alpha: 1) // #c7cecf
    static let textBright = NSColor(srgbRed: 0.9255, green: 0.9451, blue: 0.9490, alpha: 1) // #ecf1f2

    // Identity. Used for the resting ring only — never to signal a state.
    static let accent     = NSColor(srgbRed: 0.0000, green: 0.6588, blue: 0.8314, alpha: 1) // #00a8d4

    // States. Ranked worst-wins by the tile.
    static let info       = NSColor(srgbRed: 0.3098, green: 0.8039, blue: 0.8039, alpha: 1) // #4fcdcd  — working
    static let warning    = NSColor(srgbRed: 0.9451, green: 0.7490, blue: 0.3059, alpha: 1) // #f1bf4e  — needs attention
    static let error      = NSColor(srgbRed: 0.9490, green: 0.3059, blue: 0.3373, alpha: 1) // #f24e56  — failed

    // Lifted for the notch island, which sits on bgChrome.
    static let infoUp     = NSColor(srgbRed: 0.5020, green: 0.8980, blue: 0.8941, alpha: 1) // #80e5e4
    static let warningUp  = NSColor(srgbRed: 1.0000, green: 0.8510, blue: 0.5333, alpha: 1) // #ffd988
    static let errorUp    = NSColor(srgbRed: 1.0000, green: 0.5843, blue: 0.5725, alpha: 1) // #ff9592
    static let accentUp   = NSColor(srgbRed: 0.4392, green: 0.8471, blue: 1.0000, alpha: 1) // #70d8ff
}
