// GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.
// Ember tokens for the CmuxDock tile.

import AppKit

enum Iris {
    static let bgBase     = NSColor(srgbRed: 0.0588, green: 0.0353, blue: 0.0275, alpha: 1) // #0f0907
    static let bgRaised   = NSColor(srgbRed: 0.0980, green: 0.0706, blue: 0.0588, alpha: 1) // #19120f
    static let bgPanel    = NSColor(srgbRed: 0.1412, green: 0.1098, blue: 0.0980, alpha: 1) // #241c19
    static let bgChrome   = NSColor(srgbRed: 0.2824, green: 0.2471, blue: 0.2314, alpha: 1) // #483f3b  — system bar / notch island
    static let border     = NSColor(srgbRed: 0.2627, green: 0.2235, blue: 0.2078, alpha: 1) // #433935
    static let textDim    = NSColor(srgbRed: 0.4863, green: 0.4471, blue: 0.4353, alpha: 1) // #7c726f
    static let text       = NSColor(srgbRed: 0.8196, green: 0.7922, blue: 0.7843, alpha: 1) // #d1cac8
    static let textBright = NSColor(srgbRed: 0.9529, green: 0.9373, blue: 0.9294, alpha: 1) // #f3efed

    // Identity. Used for the resting ring only — never to signal a state.
    static let accent     = NSColor(srgbRed: 0.9608, green: 0.5059, blue: 0.0588, alpha: 1) // #f5810f

    // States. Ranked worst-wins by the tile.
    static let info       = NSColor(srgbRed: 0.3098, green: 0.8039, blue: 0.8039, alpha: 1) // #4fcdcd  — working
    static let warning    = NSColor(srgbRed: 0.9451, green: 0.7490, blue: 0.3059, alpha: 1) // #f1bf4e  — needs attention
    static let error      = NSColor(srgbRed: 0.9490, green: 0.3059, blue: 0.3373, alpha: 1) // #f24e56  — failed

    // Lifted for the notch island, which sits on bgChrome.
    static let infoUp     = NSColor(srgbRed: 0.5020, green: 0.8980, blue: 0.8941, alpha: 1) // #80e5e4
    static let warningUp  = NSColor(srgbRed: 1.0000, green: 0.8510, blue: 0.5333, alpha: 1) // #ffd988
    static let errorUp    = NSColor(srgbRed: 1.0000, green: 0.5843, blue: 0.5725, alpha: 1) // #ff9592
    static let accentUp   = NSColor(srgbRed: 1.0000, green: 0.7137, blue: 0.5216, alpha: 1) // #ffb685
}
