#!/usr/bin/env bash
# GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.
# Iris palette for sketchybar. 0xAARRGGBB.

# ── Ramp ───────────────────────────────────────────────────────────────────
export INK0=0xff0a090f
export INK1=0xff14131a
export INK2=0xff1e1d25
export INK3=0xff2a2932
export INK4=0xff3c3a44
export INK5=0xff55545d
export INK6=0xff74737c
export INK7=0xff9e9da5
export INK8=0xffcccbd1
export INK9=0xfff0eff3

# ── Named slots (referenced by sketchybarrc and plugins/) ──────────────────
export BLACK=0xff0a090f
export WHITE=0xffcccbd1
export GREY=0xff74737c
# Lifted variants: these are drawn ON the bar, which is much lighter than a
# terminal, and the normal set drops under 3:1 there.
export RED=0xffff9592
export GREEN=0xff89eb9f
export YELLOW=0xffffd988
export ORANGE=0xffffd988
export BLUE=0xffb6ceff
export CYAN=0xff80e5e4
export MAGENTA=0xffbe84fb
export TRANSPARENT=0x00000000

# ── Semantic ───────────────────────────────────────────────────────────────
export ACCENT=0xffbe84fb
export ACCENT_TRANSPARENT=0x45be84fb
export GREY_TRANSP=0x4574737c

# The bar itself is translucent so the wallpaper reads through; items sit on
# opaque-enough fills to keep their labels legible over any wallpaper region.
export BAR_COLOR=0x6b414048
export BG0=0xcc414048
export BG1=0x8c414048
export BG2=0xb8414048

export ITEM_BG=0x61414048
export ITEM_BG_ACTIVE=0xab301d43

# ── Fonts ──────────────────────────────────────────────────────────────────
# Exported here because every plugin already sources this file. Plugins used
# to hardcode "SF Pro", which is NOT installed on this machine — sketchybar
# silently falls back on an unknown family rather than erroring, so the icons
# rendered as tofu boxes while the config looked correct.
# Every glyph in icons.sh is verified against FONT_ICON's cmap table.
export FONT_UI="Helvetica Neue"
export FONT_ICON="JetBrainsMono Nerd Font"
