#!/usr/bin/env bash
# GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.
# Fucsia palette for sketchybar. 0xAARRGGBB.

# ── Ramp ───────────────────────────────────────────────────────────────────
export INK0=0xff0c090d
export INK1=0xff161218
export INK2=0xff211c23
export INK3=0xff2d282f
export INK4=0xff3f3941
export INK5=0xff59535b
export INK6=0xff78727a
export INK7=0xffa19ca3
export INK8=0xffcecbd0
export INK9=0xfff1eff2

# ── Named slots (referenced by sketchybarrc and plugins/) ──────────────────
export BLACK=0xff0c090d
export WHITE=0xffcecbd0
export GREY=0xff78727a
# Lifted variants: these are drawn ON the bar, which is much lighter than a
# terminal, and the normal set drops under 3:1 there.
export RED=0xffff9592
export GREEN=0xff89eb9f
export YELLOW=0xffffd988
export ORANGE=0xffffd988
export BLUE=0xffb6ceff
export CYAN=0xff80e5e4
export MAGENTA=0xffe077d8
export TRANSPARENT=0x00000000

# ── Semantic ───────────────────────────────────────────────────────────────
export ACCENT=0xffe077d8
export ACCENT_TRANSPARENT=0x45e077d8
export GREY_TRANSP=0x4578727a

# The bar itself is translucent so the wallpaper reads through; items sit on
# opaque-enough fills to keep their labels legible over any wallpaper region.
export BAR_COLOR=0x6b443f46
export BG0=0xcc443f46
export BG1=0x8c443f46
export BG2=0xb8443f46

export ITEM_BG=0x61443f46
export ITEM_BG_ACTIVE=0xab3a1938

# ── Fonts ──────────────────────────────────────────────────────────────────
# Exported here because every plugin already sources this file. Plugins used
# to hardcode "SF Pro", which is NOT installed on this machine — sketchybar
# silently falls back on an unknown family rather than erroring, so the icons
# rendered as tofu boxes while the config looked correct.
# Every glyph in icons.sh is verified against FONT_ICON's cmap table.
export FONT_UI="Helvetica Neue"
export FONT_ICON="JetBrainsMono Nerd Font"
