#!/usr/bin/env node
// Emits the colour layer of every config from tools/tokens.mjs.
//
//   node tools/build.mjs           write generated files
//   node tools/build.mjs --check   fail if any generated file is out of date
//
// Palette drift across apps is the exact bug this repo used to have (four
// different neutral families under one accent). Generating instead of
// hand-editing makes that failure mode structurally impossible.

import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ink, accent, state, surfaceTint, semantic, ansi, categorical, meta } from './tokens.mjs';
import { argb, bare, hex } from './color.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const BANNER = 'GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.';

const out = [];
function emit(relPath, content) {
  out.push({ relPath, content });
}

// ── pi theme ────────────────────────────────────────────────────────────────
// The schema is additionalProperties:false with 52 valid keys, so every key
// below is required to exist and no others may appear.
//
// NOTE: values are literal hex, with no `vars` indirection. pi resolves `vars`
// at load time and a single typo in a var name silently falls back to the
// stock dark theme with no error — the previous theme was one character away
// from that failure because its var names shadowed token names
// (`"borderMuted": "borderMuted"`). Generated output has no reason to indirect.
const piTheme = {
  $schema:
    'https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json',
  name: meta.slug,
  colors: {
    accent: accent.base,
    // Neutral, NOT accent: pi runs inside a cmux pane that already draws an
    // accent-coloured focus border. Two nested accent outlines is the
    // "stacked focus rings" problem — see docs/DESIGN.md.
    border: ink[5],
    borderAccent: accent.base,
    borderMuted: ink[4],

    success: state.success,
    error: state.error,
    warning: state.warning,
    muted: ink[7],
    dim: ink[6],
    text: ink[8],
    thinkingText: ink[6],

    selectedBg: accent.wash,
    userMessageBg: ink[2],
    userMessageText: ink[8],
    customMessageBg: surfaceTint.special,
    customMessageText: ink[8],
    customMessageLabel: state.special,
    toolPendingBg: surfaceTint.pending,
    toolSuccessBg: surfaceTint.success,
    toolErrorBg: surfaceTint.error,
    // Bright neutral rather than accent: tool titles appear on nearly every
    // line of a session. Accent-colouring them would drown the accent.
    toolTitle: ink[9],
    toolOutput: ink[7],

    mdHeading: accent.bright,
    mdLink: state.info,
    mdLinkUrl: ink[6],
    mdCode: state.warning,
    mdCodeBlock: ink[8],
    mdCodeBlockBorder: ink[4],
    mdQuote: ink[7],
    mdQuoteBorder: accent.deep,
    mdHr: ink[4],
    mdListBullet: accent.base,

    toolDiffAdded: state.success,
    toolDiffRemoved: state.error,
    toolDiffContext: ink[6],

    // Syntax hierarchy by frequency: the things you skim past are dimmest,
    // the things that carry structure are brightest.
    syntaxComment: ink[6],
    syntaxKeyword: state.special,
    syntaxFunction: accent.base,
    syntaxVariable: ink[8],
    syntaxString: state.success,
    syntaxNumber: state.warning,
    syntaxType: state.info,
    syntaxOperator: accent.dim,
    syntaxPunctuation: ink[7],

    // A heat ramp — reasoning effort climbs from cold neutral through the
    // accent into amber. Reads as intensity, not as five unrelated colours.
    thinkingOff: ink[5],
    thinkingMinimal: accent.deep,
    thinkingLow: accent.dim,
    thinkingMedium: accent.base,
    thinkingHigh: accent.bright,
    thinkingXhigh: state.warning,
    thinkingMax: ansi.brightYellow,

    bashMode: state.info,
  },
  // Only these three keys are permitted, and they affect /export HTML only.
  export: { pageBg: ink[0], cardBg: ink[1], infoBg: ink[2] },
};
emit(`pi/themes/${meta.slug}.json`, JSON.stringify(piTheme, null, 2) + '\n');

// ── ghostty theme ───────────────────────────────────────────────────────────
// Shipped as a theme FILE rather than inline keys, so `theme = iris` in the
// main config stays readable and the palette can be swapped atomically.
const ghosttyTheme = `# ${BANNER}
# ${meta.name} — ${meta.appearance}

palette = 0=#${bare(ansi.black)}
palette = 1=#${bare(ansi.red)}
palette = 2=#${bare(ansi.green)}
palette = 3=#${bare(ansi.yellow)}
palette = 4=#${bare(ansi.blue)}
palette = 5=#${bare(ansi.magenta)}
palette = 6=#${bare(ansi.cyan)}
palette = 7=#${bare(ansi.white)}
palette = 8=#${bare(ansi.brightBlack)}
palette = 9=#${bare(ansi.brightRed)}
palette = 10=#${bare(ansi.brightGreen)}
palette = 11=#${bare(ansi.brightYellow)}
palette = 12=#${bare(ansi.brightBlue)}
palette = 13=#${bare(ansi.brightMagenta)}
palette = 14=#${bare(ansi.brightCyan)}
palette = 15=#${bare(ansi.brightWhite)}

background = #${bare(semantic.bgBase)}
foreground = #${bare(semantic.text)}

cursor-color = #${bare(accent.base)}
cursor-text = #${bare(ink[0])}

selection-background = #${bare(accent.wash)}
selection-foreground = #${bare(ink[9])}
`;
emit('ghostty/themes/' + meta.slug, ghosttyTheme);

// ── sketchybar colours ──────────────────────────────────────────────────────
// Variable NAMES are load-bearing: sketchybarrc and every plugin script
// reference them. Renaming a variable silently yields a transparent item, so
// the existing names are preserved and only their values change.
const sb = `#!/usr/bin/env bash
# ${BANNER}
# ${meta.name} palette for sketchybar. 0xAARRGGBB.

# ── Ramp ───────────────────────────────────────────────────────────────────
export INK0=${argb(ink[0])}
export INK1=${argb(ink[1])}
export INK2=${argb(ink[2])}
export INK3=${argb(ink[3])}
export INK4=${argb(ink[4])}
export INK5=${argb(ink[5])}
export INK6=${argb(ink[6])}
export INK7=${argb(ink[7])}
export INK8=${argb(ink[8])}
export INK9=${argb(ink[9])}

# ── Named slots (referenced by sketchybarrc and plugins/) ──────────────────
export BLACK=${argb(ink[0])}
export WHITE=${argb(ink[8])}
export GREY=${argb(ink[6])}
export RED=${argb(state.error)}
export GREEN=${argb(state.success)}
export YELLOW=${argb(state.warning)}
export ORANGE=${argb(state.warning)}
export BLUE=${argb(state.special)}
export CYAN=${argb(state.info)}
export MAGENTA=${argb(accent.base)}
export TRANSPARENT=0x00000000

# ── Semantic ───────────────────────────────────────────────────────────────
export ACCENT=${argb(accent.base)}
export ACCENT_TRANSPARENT=${argb(accent.base, 0.27)}
export GREY_TRANSP=${argb(ink[6], 0.27)}

# The bar itself is translucent so the wallpaper reads through; items sit on
# opaque-enough fills to keep their labels legible over any wallpaper region.
export BAR_COLOR=${argb(ink[0], 0.4)}
export BG0=${argb(ink[0], 0.8)}
export BG1=${argb(ink[1], 0.67)}
export BG2=${argb(ink[2], 0.8)}

export ITEM_BG=${argb(ink[2], 0.4)}
export ITEM_BG_ACTIVE=${argb(accent.wash, 0.67)}

# ── Fonts ──────────────────────────────────────────────────────────────────
# Exported here because every plugin already sources this file. Plugins used
# to hardcode "SF Pro", which is NOT installed on this machine — sketchybar
# silently falls back on an unknown family rather than erroring, so the icons
# rendered as tofu boxes while the config looked correct.
# Every glyph in icons.sh is verified against FONT_ICON's cmap table.
export FONT_UI="Helvetica Neue"
export FONT_ICON="JetBrainsMono Nerd Font"
`;
emit('sketchybar/colors.sh', sb);

// ── borders ─────────────────────────────────────────────────────────────────
// Width is deliberately thinner than the old 8.0: the window border is the
// OUTERMOST ring in a three-level focus hierarchy (window → cmux pane → nvim
// split). The outermost ring only needs to be found, not shouted.
const borders = `#!/bin/bash
# ${BANNER}
# ${meta.name} — window focus ring (outermost level of the focus hierarchy).

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=${argb(accent.base)}
  inactive_color=${argb(ink[4], 0.53)}
)

borders "\${options[@]}"
`;
emit('borders/bordersrc', borders);

// ── cmux ────────────────────────────────────────────────────────────────────
// Generated whole rather than colour-only: it is pure declarative config, and
// generating it is what guarantees the palette cannot drift from the rest.
// Every key below was checked against the published schema; unknown keys are
// rejected by `tools/check-configs.sh`.
//
// NOTE: cmux takes its TERMINAL palette from ~/.config/ghostty/config, not
// from this file (`cmux themes list` confirms it resolves theme `iris` from
// there). So this file only styles cmux's own chrome.
const cmux = {
  $schema: 'https://raw.githubusercontent.com/manaflow-ai/cmux/main/web/data/cmux.schema.json',
  schemaVersion: 1,

  // Focus hierarchy, level 2 of 3. Each level uses a DIFFERENT mechanism so
  // they can never read as competing rings:
  //   1. window  — JankyBorders, thick 4px accent ring outside the window
  //   2. pane    — this, a thin accent line inside the window
  //   3. split   — Ghostty dims unfocused content, drawing no border at all
  paneBorderColor: ink[4],
  activePaneBorderColor: accent.base,

  app: {
    appearance: 'dark',
    appIcon: 'dark',
    minimalMode: false,
    newWorkspacePlacement: 'afterCurrent',
    workspaceInheritWorkingDirectory: true,
    confirmQuit: 'dirty-only',
    reorderOnNotification: true,
    // Keyboard navigation: make the palette and focus-cycling reach
    // everything, so the mouse is never required to get somewhere.
    commandPaletteSearchesAllSurfaces: true,
    focusHistoryIncludesPanesAndTabs: true,
    focusPaneOnFirstClick: true,
    openMarkdownInCmuxViewer: true,
  },

  terminal: {
    sessionContentAlignment: 'center',
    sessionContentMaxWidth: false,
    showScrollBar: true,
    scrollSpeed: 1,
    autoResumeAgentSessions: true,
    // Matches Ghostty's copy-on-select so selection behaves identically
    // whichever terminal surface you happen to be in.
    copyOnSelect: true,
  },

  notifications: {
    unreadPaneRing: true,
    // paneFlash is OFF deliberately. The unread ring already owns "this pane
    // has news", and a flashing pane edge competes with the focus border for
    // the same visual channel — a coloured edge. Two unrelated meanings, one
    // treatment, which is the confusion this system exists to prevent.
    paneFlash: false,
    dockBadge: true,
    showInMenuBar: true,
    sound: 'default',
    // Never interrupt about the pane already being looked at.
    suppressOnlyFocusedSurface: true,
    // Sound and banner only when actually away from the machine.
    agentTurnComplete: 'whenIdle',
    agentIdleReminder: true,
    agentPermissionPrompt: true,
  },

  sidebar: {
    hideAllDetails: false,
    showBranchDirectory: true,
    showWorkspaceDescription: true,
    showNotificationMessage: true,
    showAgentActivity: true,
    showProgress: true,
    showPullRequests: true,
    makePullRequestsClickable: true,
    showPorts: true,
    showSSH: true,
    showLog: true,
    openPortLinksInCmuxBrowser: true,
    openPullRequestLinksInCmuxBrowser: true,
    watchGitStatus: true,
    wrapWorkspaceTitles: false,
    branchLayout: 'vertical',
    // 8 lines of notification text per row pushed real workspaces off screen
    // on a laptop display. 5 keeps the gist without costing a workspace slot.
    notificationMessageLineLimit: 5,
    // Split the two indicators to opposite ends: a spinner (transient, "busy")
    // and a badge (persistent, "unread") mean different things and must not
    // trade places in the same spot.
    loadingSpinnerPosition: 'leading',
    notificationBadgePosition: 'trailing',
  },

  workspaceColors: {
    indicatorStyle: 'washRail',
    selectionColor: accent.wash,
    // Amber, NOT the accent. The previous config used the accent colour here,
    // which made "this workspace is selected" and "this workspace needs you"
    // the same colour. Attention is a STATUS; the accent is IDENTITY.
    notificationBadgeColor: state.warning,
    colors: categorical,
  },

  sidebarAppearance: {
    matchTerminalBackground: true,
    tintColor: ink[1],
    darkModeTintColor: ink[1],
    lightModeTintColor: null,
    tintOpacity: 0.18,
  },

  automation: {
    claudeCodeIntegration: true,
    geminiIntegration: true,
    suppressSubagentNotifications: true,
    socketControlMode: 'cmuxOnly',
  },

  browser: {
    theme: 'dark',
    openTerminalLinksInCmuxBrowser: true,
    interceptTerminalOpenCommandInCmuxBrowser: true,
  },

  diffViewer: {
    defaultLayout: 'split',
  },

  markdown: {
    fontSize: 15,
    // Empty = cmux's proportional system font. The previous config forced
    // JetBrainsMono here, so every README and PR body was read in monospace.
    // Monospace is right for code and wrong for prose.
    fontFamily: '',
    // 980px at 15px proportional is ~120 characters per line — far past the
    // ~70-80 where reading speed drops off.
    maxWidth: 760,
  },
};
emit('cmux/cmux.json', JSON.stringify(cmux, null, 2) + '\n');

// ── wallpaper ──────────────────────────────────────────────────────────────
// Rendered by tools/wallpaper.mjs, not here: this machine has no working SVG
// rasteriser, so the wallpapers are drawn pixel-by-pixel instead.

// ── write / check ───────────────────────────────────────────────────────────
let stale = 0;
for (const { relPath, content } of out) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (CHECK) {
    if (current !== content) {
      stale++;
      console.log(`  STALE  ${relPath}`);
    } else {
      console.log(`  ok     ${relPath}`);
    }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`  ${current === content ? 'unchanged' : 'wrote    '}  ${relPath}`);
  }
}

if (CHECK) {
  console.log(stale === 0 ? '\nPASS — generated files match tokens.' : `\nFAIL — ${stale} stale.`);
  process.exit(stale === 0 ? 0 : 1);
}
